services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  customer_microservice:
    build: ./microservices/customer-service
    volumes:
      - ./microservices/customer-service/src:/usr/src/app/src
    command: npm run start:dev
  policy_microservice:
    build: ./microservices/policy-service
    volumes:
      - ./microservices/policy-service/src:/usr/src/app/src
    command: npm run start:dev
  nats-server:
    image: nats
    ports:
      - 4222:4222
